### ISSUE TITLE
Missing .eslintrc file in STARTERKIT

### ISSUE THREAD

**Issue by Hypocrite** [acquia-pso/cog#143]
When running the gulp task and ESLint fails, I receive the following error:
```Error: No ESLint configuration found.
at Config.getLocalConfigHierarchy (/var/www/drupalvm/test/drupal/themes/test_cog/node_modules/eslint/lib/config.js:256:39)
at Config.getConfigHierarchy (/var/www/drupalvm/test/drupal/themes/test_cog/node_modules/eslint/lib/config.js:180:43)
at Config.getConfigVector (/var/www/drupalvm/test/drupal/themes/test_cog/node_modules/eslint/lib/config.js:287:21)
at Config.getConfig (/var/www/drupalvm/test/drupal/themes/test_cog/node_modules/eslint/lib/config.js:330:29)
at processText (/var/www/drupalvm/test/drupal/themes/test_cog/node_modules/eslint/lib/cli-engine.js:162:33)
at CLIEngine.executeOnText (/var/www/drupalvm/test/drupal/themes/test_cog/node_modules/eslint/lib/cli-engine.js:618:17)
at Transform.util.transform [as _transform] (/var/www/drupalvm/test/drupal/themes/test_cog/node_modules/gulp-eslint/index.js:50:20)
at Transform._read (_stream_transform.js:186:10)
at Transform._write (_stream_transform.js:174:12)
at doWrite (_stream_writable.js:387:12)
at writeOrBuffer (_stream_writable.js:373:5)
at Transform.Writable.write (_stream_writable.js:290:11)
at write (/var/www/drupalvm/test/drupal/themes/test_cog/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:623:24)
at flow (/var/www/drupalvm/test/drupal/themes/test_cog/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:632:7)
at DestroyableTransform.pipeOnReadable (/var/www/drupalvm/test/drupal/themes/test_cog/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:664:5)
at emitNone (events.js:106:13)```

There seems to be no .eslintrc file in the STARTERKIT folder. The error message goes away if you add the .eslintrc file to the subtheme.

**Comment by sarahjean** [comment]
Closing unless there is further info.

**Comment by Hypocrite** [comment]
Sorry for the late reply.
My docroot is /var/www/drupalvm/drupal/web/, but currently the subtheme is symlinked from Git, so thats probably the reason why ESLint is failing to find the file.

**Comment by sarahjean** [comment]
@Hypocrite thanks for the update. In that case, it's probably best for you to go ahead and add yourself a custom config for eslint to your subtheme, or symlink the core one, whichever you feel more comfortable with.
